on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create _data directory
        run: |
          mkdir _data
          cd _data
      
      - name: Create file pass
        run: |
          touch pass.yml
          FILE="pass.yml"
          cat <<EOF >$FILE
          text: >-
            This is fantastic
          num: 56
          list:
            - first fun
            - then run
          EOF
          cd ..
      
      - uses: actions/upload-artifact@v3
        with:
          name: data
          path: _data