on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create _data directory
        run: |
          mkdir _data
          ls -a
          cd _data
      
      - name: Create file pass
        run: |
          touch pass.yml
          FILE="pass.yml"
          cat <<EOF >$FILE
          text: >-
            This is fantastic
          num: 56
          list:
            - first fun
            - then run
          EOF
          cd ..
          ls -a
          cd jekyll-site
          ls -a
      
      - uses: actions/jekyll-build-pages@v1
        with:
          source: .
          destination: ./_site
          future: false
          verbose: true
          token: ${{ github.token }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
          clean: true
